### ISSUE TITLE
Error in running matplotlib

### ISSUE THREAD

**Issue by tprodanov** [NBISweden/IgDiscover#82]
Running IgDiscover on a test dataset fails on the following job:
`igdiscover group --pseudo-cdr3=-80:-60 --groups-output=reads/groups.tab.gz --barcode-length=12 --trim-g --plot-sizes=stats/groupsizes.pdf reads/5-filtered.fasta`
with the following mistake:
```Traceback (most recent call last):
  File "/home/tprodanov/.miniconda3/envs/competitors/bin/igdiscover", line 11, in <module>
    load_entry_point('igdiscover==0.6.0', 'console_scripts', 'igdiscover')()
  File "/home/tprodanov/.miniconda3/envs/competitors/lib/python3.5/site-packages/igdiscover-0.6.0-py3.5.egg/igdiscover/__main__.py", line 67, in main
  File "/home/tprodanov/.miniconda3/envs/competitors/lib/python3.5/site-packages/igdiscover-0.6.0-py3.5.egg/igdiscover/group.py", line 313, in main
  File "/home/tprodanov/.local/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 2938, in tick_params
    self.xaxis.set_tick_params(**xkw)
  File "/home/tprodanov/.local/lib/python3.5/site-packages/matplotlib/axis.py", line 867, in set_tick_params
    tick._apply_params(**self._major_tick_kw)
  File "/home/tprodanov/.local/lib/python3.5/site-packages/matplotlib/axis.py", line 352, in _apply_params
    self.apply_tickdir(kw.pop('tickdir', self._tickdir))
  File "/home/tprodanov/.local/lib/python3.5/site-packages/matplotlib/axis.py", line 432, in apply_tickdir
    self._pad = self._base_pad + self.get_tick_padding()
  File "/home/tprodanov/.local/lib/python3.5/site-packages/matplotlib/axis.py", line 224, in get_tick_padding
    return self._size * padding[self._tickdir]
KeyError: 'outward'
```

I have Matplotlib 2.2.2, but downgrading to 1.5.1 did not help, there was the same error.

**Comment by tprodanov** [comment]
Thank you! I did not notice the version

**Comment by marcelm** [comment]
Great, closing this then.
