### ISSUE TITLE
Running light chain sequences

### ISSUE THREAD

**Issue by ayeletperes** [NBISweden/IgDiscover#92]
When running light chain sequences it fails during igblast run. 

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/../.conda/envs/igdiscover3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/../.conda/envs/igdiscover3/lib/python3.6/site-packages/igdiscover/igblast.py", line 210, in __call__
    records = list(parser)
  File "/home/../.conda/envs/igdiscover3/lib/python3.6/site-packages/igdiscover/parse.py", line 629, in __iter__
    yield self._parse_record(record_lines, fasta_record)
  File "/home/../.conda/envs/igdiscover3/lib/python3.6/site-packages/igdiscover/parse.py", line 709, in _parse_record
    assert qsequence == full_sequence[hit.query_start:hit.query_start+len(qsequence)]
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/../.conda/envs/igdiscover3/bin/igdiscover", line 11, in <module>
    load_entry_point('igdiscover==0.10', 'console_scripts', 'igdiscover')()
  File "/home/../.conda/envs/igdiscover3/lib/python3.6/site-packages/igdiscover/__main__.py", line 89, in main
    args.func(args)
  File "/home/../.conda/envs/igdiscover3/lib/python3.6/site-packages/igdiscover/igblast.py", line 350, in main
    raw_output=raw_output):
  File "/home/../.conda/envs/igdiscover3/lib/python3.6/site-packages/igdiscover/igblast.py", line 325, in igblast
    for igblast_output, igblast_records in pool.imap(runner, chunks, chunksize=1):
  File "/home/../.conda/envs/igdiscover3/lib/python3.6/multiprocessing/pool.py", line 761, in next
    raise value
AssertionError

BLAST Database error: Error: File (/tmp/tmpdgdtii9q/V.nhr) not found.

**Comment by marcelm** [comment]
Interesting, we haven’t seen that before. How did you install IgDiscover? Through Conda?

Would you be able to (privately) provide me with the dataset that you are analyzing (the two FASTQ files and the V/D/J.fasta files)? I actually only need the one sequence that IgDiscover chokes on, so if you are concerned with giving your full data away, you can try to omit the reads that were processed successfully. You can get a hint where in the data that might be by looking at the `igdiscover igblast` output, where it gives you the `INFO: Processed     xyz,000 sequences at x.yz ms/sequence` lines.

**Comment by ayeletperes** [comment]
I've created an environment with conda and installed igDiscover.

I think I figured the issue, some of the sequences in the fasta files I ran
had hyphens in the sequences, used to represent gaps.
I ran the sequences in IgBlast site and they passed ok, but in
igDiscover they seem to cause an error.  I'll be happy to send you the
problematic sequences.

**Comment by marcelm** [comment]
Hm, yes, that could indeed be the problem. I would like to at least improve the error message that IgDiscover prints, so it would be nice if you could mail one of those sequences to marcel.martin@scilifelab.se.
